backend:
    name: git-gateway
    branch: main

publish_mode: editorial_workflow
media_folder: public/images
public_folder: /images
site_url: "https://www.monolithon.com/" # your site name

collections:
    - name: english-post
      label: "English Posts"
      folder: src/content/blog/en
      create: true
      format: frontmatter
      preview_path: post/{{slug}}
      fields:
          - { name: title, label: Title }
          - { label: "Draft", name: "isDraft", widget: "boolean", default: false }
          - { name: author, label: Author }
          - { name: tags, label: Tags, widget: array }
          - { name: snippet, label: Snippet, widget: string }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { name: category, label: Category, widget: array }
          - { name: body, label: Body, widget: markdown }
    - name: hu-post
      label: "Hungary Posts"
      folder: src/content/blog/hu
      create: true
      format: frontmatter
      preview_path: post/{{slug}}
      fields:
          - { name: title, label: Title }
          - { label: "Draft", name: "isDraft", widget: "boolean", default: false }
          - { name: author, label: Author }
          - { name: tags, label: Tags, widget: array }
          - { name: snippet, label: Snippet, widget: string }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { name: category, label: Category, widget: array }
          - { name: body, label: Body, widget: markdown }
